"""Module type information based on docs/module.md"""
from dataclasses import dataclass
from typing import Dict

from .const import (
    PLATINE_HW_IS_S4,
    PLATINE_HW_IS_S32,
    PLATINE_HW_IS_UP_GL,
    PLATINE_HW_IS_AR6,
    PLATINE_HW_IS_AJ3,
    PLATINE_HW_IS_AD3,
    PLATINE_HW_IS_AD3e,
    PLATINE_HW_IS_AT8,
    PLATINE_HW_IS_AT2E,
    PLATINE_HW_IS_AR2,
    PLATINE_HW_IS_AJ1,
    PLATINE_HW_IS_A32,
    PLATINE_HW_IS_TLH,
    PLATINE_HW_IS_UP_T,
    PLATINE_HW_IS_ALARM1,
    PLATINE_HW_IS_EXT_LD,
    PLATINE_HW_IS_HS_ACCESS,
    PLATINE_HW_IS_I2_PIR,
    PLATINE_HW_IS_LCD3,
    PLATINE_HW_IS_HS_WZ,
    PLATINE_HW_IS_GSM,
    PLATINE_HW_IS_HS_CLIMATE,
    PLATINE_HW_IS_HS_JAL,
    PLATINE_HW_IS_HS_TIME,
    PLATINE_HW_IS_IRRX,
    PLATINE_HW_IS_IR_TX16,
    PLATINE_HW_IS_HFRX,
    PLATINE_HW_IS_HFRXT,
    PLATINE_HW_IS_HFRX_ELV868,
    PLATINE_HW_IS_BELL2,
    PLATINE_HW_IS_19_AMP4,
    PLATINE_HW_IS_HS_SI6,
    PLATINE_HW_IS_UP_SI,
    PLATINE_HW_IS_DALI,
    PLATINE_HW_IS_HS_COUNTER,
    PLATINE_HW_IS_ACCESS2_MAIN,
    PLATINE_HW_IS_PROUTE1,
    PLATINE_HW_IS_EXT_AQV_PW,
    PLATINE_HW_IS_EXT_CBE,
    PLATINE_HW_IS_PC_SOFTWARE,
    PLATINE_HW_IS_UP_RF,
    PLATINE_HW_IS_UP_RF2,
)


@dataclass
class ModuleTypeInfo:
    """Information about a module type from module.md"""
    typ: int  # PLATINE_HW_IS_* constant
    description: str
    ns: int  # Number of sensors
    na: int  # Number of actors
    ng: int  # Length of group table
    nm: int  # Length of ModulSpec table
    sw1: int  # Software version USER1
    sw2: int  # Software version USER2
    swIPK1: int  # IPK version 1
    swIPK2: int  # IPK version 2
    i0: int  # Current consumption in mA
    dlg_idx: int = 0  # Dialog index (default: 0)


# Dictionary with all module types from module.md
MODULE_TYPES: Dict[int, ModuleTypeInfo] = {
    # Sensors
    PLATINE_HW_IS_S4: ModuleTypeInfo(
        typ=PLATINE_HW_IS_S4,
        description="Sensor, 4fach",
        ns=4,
        na=0,
        ng=0,
        nm=0,
        sw1=1,
        sw2=15,
        swIPK1=4,
        swIPK2=4,
        i0=18,
    ),
    PLATINE_HW_IS_S32: ModuleTypeInfo(
        typ=PLATINE_HW_IS_S32,
        description="Sensor, 32fach (beta)",
        ns=32,
        na=0,
        ng=0,
        nm=0,
        sw1=1,
        sw2=2,
        swIPK1=4,
        swIPK2=4,
        i0=50,
    ),
    PLATINE_HW_IS_UP_GL: ModuleTypeInfo(
        typ=PLATINE_HW_IS_UP_GL,
        description="Sensor, Glasbruch",
        ns=1,
        na=0,
        ng=0,
        nm=0,
        sw1=1,
        sw2=10,
        swIPK1=4,
        swIPK2=3,
        i0=55,
    ),
    # Actors
    PLATINE_HW_IS_AR6: ModuleTypeInfo(
        typ=PLATINE_HW_IS_AR6,
        description="Aktor, Relais, 6A 6fach",
        ns=0,
        na=6,
        ng=80,
        nm=0,
        sw1=2,
        sw2=0,
        swIPK1=4,
        swIPK2=4,
        i0=125,
    ),
    PLATINE_HW_IS_AJ3: ModuleTypeInfo(
        typ=PLATINE_HW_IS_AJ3,
        description="Aktor, Jalousie, 3A 3fach",
        ns=0,
        na=3,
        ng=80,
        nm=0,
        sw1=2,
        sw2=1,
        swIPK1=4,
        swIPK2=4,
        i0=125,
    ),
    PLATINE_HW_IS_AD3: ModuleTypeInfo(
        typ=PLATINE_HW_IS_AD3,
        description="Aktor, Dimmer, 575VA 3fach",
        ns=0,
        na=3,
        ng=80,
        nm=0,
        sw1=1,
        sw2=18,
        swIPK1=4,
        swIPK2=4,
        i0=40,
    ),
    PLATINE_HW_IS_AD3e: ModuleTypeInfo(
        typ=PLATINE_HW_IS_AD3e,
        description="Aktor, Dimmer-E, 575VA 3fach",
        ns=0,
        na=3,
        ng=80,
        nm=0,
        sw1=1,
        sw2=18,
        swIPK1=4,
        swIPK2=4,
        i0=40,
    ),
    PLATINE_HW_IS_AT8: ModuleTypeInfo(
        typ=PLATINE_HW_IS_AT8,
        description="Aktor, Elektronik, 25VA 8fach",
        ns=0,
        na=8,
        ng=80,
        nm=0,
        sw1=2,
        sw2=0,
        swIPK1=4,
        swIPK2=4,
        i0=50,
    ),
    PLATINE_HW_IS_AT2E: ModuleTypeInfo(
        typ=PLATINE_HW_IS_AT2E,
        description="Aktor, Elektronik, 25VA 2fach",
        ns=0,
        na=2,
        ng=80,
        nm=0,
        sw1=1,
        sw2=0,
        swIPK1=4,
        swIPK2=3,
        i0=50,
    ),
    PLATINE_HW_IS_AR2: ModuleTypeInfo(
        typ=PLATINE_HW_IS_AR2,
        description="Aktor, Relais, 6A 2fach",
        ns=0,
        na=2,
        ng=80,
        nm=0,
        sw1=1,
        sw2=2,
        swIPK1=4,
        swIPK2=4,
        i0=50,
    ),
    PLATINE_HW_IS_AJ1: ModuleTypeInfo(
        typ=PLATINE_HW_IS_AJ1,
        description="Aktor, Jalousie, 3A 1fach",
        ns=0,
        na=1,
        ng=30,
        nm=0,
        sw1=1,
        sw2=2,
        swIPK1=4,
        swIPK2=4,
        i0=50,
    ),
    PLATINE_HW_IS_A32: ModuleTypeInfo(
        typ=PLATINE_HW_IS_A32,
        description="Aktor, 32fach (beta)",
        ns=0,
        na=32,
        ng=80,
        nm=0,
        sw1=1,
        sw2=2,
        swIPK1=4,
        swIPK2=4,
        i0=50,
    ),
    # Controllers and special modules
    PLATINE_HW_IS_TLH: ModuleTypeInfo(
        typ=PLATINE_HW_IS_TLH,
        description="Modul, Regler, Temp./Licht/Feuchte Sensor, UP-TLH",
        ns=0,
        na=0,
        ng=0,
        nm=22,
        sw1=1,
        sw2=20,
        swIPK1=4,
        swIPK2=4,
        i0=30,
    ),
    PLATINE_HW_IS_UP_T: ModuleTypeInfo(
        typ=PLATINE_HW_IS_UP_T,
        description="Modul, Regler, Temp.Sensor, UP-T",
        ns=0,
        na=0,
        ng=0,
        nm=22,
        sw1=1,
        sw2=21,
        swIPK1=4,
        swIPK2=4,
        i0=30,
    ),
    PLATINE_HW_IS_ALARM1: ModuleTypeInfo(
        typ=PLATINE_HW_IS_ALARM1,
        description="Alarmanlage",
        ns=0,
        na=0,
        ng=0,
        nm=107,
        sw1=1,
        sw2=20,
        swIPK1=4,
        swIPK2=4,
        i0=40,
    ),
    PLATINE_HW_IS_EXT_LD: ModuleTypeInfo(
        typ=PLATINE_HW_IS_EXT_LD,
        description="Motorriegel",
        ns=0,
        na=0,
        ng=0,
        nm=6,
        sw1=1,
        sw2=20,
        swIPK1=4,
        swIPK2=4,
        i0=40,
    ),
    PLATINE_HW_IS_HS_ACCESS: ModuleTypeInfo(
        typ=PLATINE_HW_IS_HS_ACCESS,
        description="Zutritts-Steuerung",
        ns=0,
        na=0,
        ng=0,
        nm=60,
        sw1=1,
        sw2=3,
        swIPK1=4,
        swIPK2=4,
        i0=40,
    ),
    PLATINE_HW_IS_I2_PIR: ModuleTypeInfo(
        typ=PLATINE_HW_IS_I2_PIR,
        description="Bewegungsmelder-Schnittstelle",
        ns=0,
        na=0,
        ng=0,
        nm=2,
        sw1=3,
        sw2=6,
        swIPK1=4,
        swIPK2=4,
        i0=40,
    ),
    PLATINE_HW_IS_LCD3: ModuleTypeInfo(
        typ=PLATINE_HW_IS_LCD3,
        description="LCD-Display",
        ns=0,
        na=0,
        ng=0,
        nm=508,
        sw1=1,
        sw2=31,
        swIPK1=4,
        swIPK2=4,
        i0=50,
    ),
    PLATINE_HW_IS_HS_WZ: ModuleTypeInfo(
        typ=PLATINE_HW_IS_HS_WZ,
        description="Wetterstation",
        ns=0,
        na=0,
        ng=0,
        nm=47,
        sw1=1,
        sw2=1,
        swIPK1=4,
        swIPK2=4,
        i0=110,
    ),
    PLATINE_HW_IS_GSM: ModuleTypeInfo(
        typ=PLATINE_HW_IS_GSM,
        description="GSM-Modul",
        ns=0,
        na=0,
        ng=0,
        nm=188,
        sw1=2,
        sw2=7,
        swIPK1=4,
        swIPK2=4,
        i0=250,
    ),
    PLATINE_HW_IS_HS_CLIMATE: ModuleTypeInfo(
        typ=PLATINE_HW_IS_HS_CLIMATE,
        description="HS-Climate",
        ns=0,
        na=0,
        ng=128,
        nm=62,
        sw1=2,
        sw2=0,
        swIPK1=4,
        swIPK2=4,
        i0=50,
    ),
    PLATINE_HW_IS_HS_JAL: ModuleTypeInfo(
        typ=PLATINE_HW_IS_HS_JAL,
        description="HS-Jal",
        ns=0,
        na=0,
        ng=128,
        nm=24,
        sw1=1,
        sw2=27,
        swIPK1=4,
        swIPK2=4,
        i0=50,
    ),
    PLATINE_HW_IS_HS_TIME: ModuleTypeInfo(
        typ=PLATINE_HW_IS_HS_TIME,
        description="Zeitsteuerung, Zeitgeber DCF, Astrokalender",
        ns=0,
        na=0,
        ng=0,
        nm=112,
        sw1=2,
        sw2=0,
        swIPK1=4,
        swIPK2=4,
        i0=35,
    ),
    # Remote controls and transmitters
    PLATINE_HW_IS_IRRX: ModuleTypeInfo(
        typ=PLATINE_HW_IS_IRRX,
        description="Remote control receiver (IR)",
        ns=0,
        na=0,
        ng=0,
        nm=32,
        sw1=1,
        sw2=10,
        swIPK1=4,
        swIPK2=4,
        i0=40,
    ),
    PLATINE_HW_IS_IR_TX16: ModuleTypeInfo(
        typ=PLATINE_HW_IS_IR_TX16,
        description="IR Universalsender V2 (16bit)",
        ns=0,
        na=0,
        ng=0,
        nm=404,
        sw1=1,
        sw2=0,
        swIPK1=4,
        swIPK2=4,
        i0=40,
    ),
    PLATINE_HW_IS_HFRX: ModuleTypeInfo(
        typ=PLATINE_HW_IS_HFRX,
        description="Remote control receiver (Radio)",
        ns=0,
        na=0,
        ng=0,
        nm=40,
        sw1=1,
        sw2=1,
        swIPK1=4,
        swIPK2=4,
        i0=40,
    ),
    PLATINE_HW_IS_HFRXT: ModuleTypeInfo(
        typ=PLATINE_HW_IS_HFRXT,
        description="Receiver for AP buttons (Radio)",
        ns=0,
        na=0,
        ng=0,
        nm=128,
        sw1=1,
        sw2=0,
        swIPK1=4,
        swIPK2=4,
        i0=40,
    ),
    PLATINE_HW_IS_HFRX_ELV868: ModuleTypeInfo(
        typ=PLATINE_HW_IS_HFRX_ELV868,
        description="Radio receiver 868Mhz (KS300)",
        ns=0,
        na=0,
        ng=0,
        nm=2,
        sw1=1,
        sw2=0,
        swIPK1=4,
        swIPK2=4,
        i0=40,
    ),
    # Other modules
    PLATINE_HW_IS_BELL2: ModuleTypeInfo(
        typ=PLATINE_HW_IS_BELL2,
        description="Komfort-Klingel",
        ns=0,
        na=0,
        ng=0,
        nm=25,
        sw1=1,
        sw2=128,
        swIPK1=4,
        swIPK2=4,
        i0=500,
    ),
    PLATINE_HW_IS_19_AMP4: ModuleTypeInfo(
        typ=PLATINE_HW_IS_19_AMP4,
        description="Amplifier 4-channel 50W",
        ns=0,
        na=0,
        ng=32,
        nm=4,
        sw1=1,
        sw2=6,
        swIPK1=4,
        swIPK2=4,
        i0=25,
    ),
    PLATINE_HW_IS_HS_SI6: ModuleTypeInfo(
        typ=PLATINE_HW_IS_HS_SI6,
        description="Stromsensor 6fach, HS-SI6",
        ns=0,
        na=0,
        ng=0,
        nm=24,
        sw1=1,
        sw2=0,
        swIPK1=4,
        swIPK2=4,
        i0=100,
    ),
    PLATINE_HW_IS_UP_SI: ModuleTypeInfo(
        typ=PLATINE_HW_IS_UP_SI,
        description="Stromsensor 1fach, UP-SI",
        ns=0,
        na=0,
        ng=0,
        nm=4,
        sw1=1,
        sw2=9,
        swIPK1=4,
        swIPK2=3,
        i0=50,
    ),
    PLATINE_HW_IS_DALI: ModuleTypeInfo(
        typ=PLATINE_HW_IS_DALI,
        description="DALI-Schnittstelle",
        ns=0,
        na=0,
        ng=16,
        nm=54,
        sw1=1,
        sw2=0,
        swIPK1=4,
        swIPK2=3,
        i0=100,
    ),
    PLATINE_HW_IS_HS_COUNTER: ModuleTypeInfo(
        typ=PLATINE_HW_IS_HS_COUNTER,
        description="Zähler",
        ns=0,
        na=0,
        ng=0,
        nm=34,
        sw1=1,
        sw2=2,
        swIPK1=4,
        swIPK2=4,
        i0=40,
    ),
    PLATINE_HW_IS_ACCESS2_MAIN: ModuleTypeInfo(
        typ=PLATINE_HW_IS_ACCESS2_MAIN,
        description="Zutritt+Zeiterfassung",
        ns=0,
        na=0,
        ng=0,
        nm=61,
        sw1=3,
        sw2=5,
        swIPK1=4,
        swIPK2=4,
        i0=40,
    ),
    PLATINE_HW_IS_PROUTE1: ModuleTypeInfo(
        typ=PLATINE_HW_IS_PROUTE1,
        description="Ablaufsteuerung, Lichtszenen",
        ns=0,
        na=0,
        ng=0,
        nm=160,
        sw1=1,
        sw2=10,
        swIPK1=4,
        swIPK2=4,
        i0=35,
    ),
    PLATINE_HW_IS_EXT_AQV_PW: ModuleTypeInfo(
        typ=PLATINE_HW_IS_EXT_AQV_PW,
        description="Badewannensteuerung",
        ns=0,
        na=0,
        ng=0,
        nm=4,
        sw1=1,
        sw2=6,
        swIPK1=4,
        swIPK2=4,
        i0=0,
    ),
    PLATINE_HW_IS_EXT_CBE: ModuleTypeInfo(
        typ=PLATINE_HW_IS_EXT_CBE,
        description="Belüftungssteuerung",
        ns=0,
        na=0,
        ng=0,
        nm=4,
        sw1=1,
        sw2=5,
        swIPK1=4,
        swIPK2=4,
        i0=0,
    ),
    PLATINE_HW_IS_PC_SOFTWARE: ModuleTypeInfo(
        typ=PLATINE_HW_IS_PC_SOFTWARE,
        description="PC-Software MMS",
        ns=0,
        na=0,
        ng=0,
        nm=0,
        sw1=1,
        sw2=5,
        swIPK1=0,
        swIPK2=0,
        i0=0,
    ),
    PLATINE_HW_IS_UP_RF: ModuleTypeInfo(
        typ=PLATINE_HW_IS_UP_RF,
        description="RF-Tag Leser V1",
        ns=2,
        na=1,
        ng=10,
        nm=0,
        sw1=1,
        sw2=12,
        swIPK1=4,
        swIPK2=4,
        i0=55,
    ),
    PLATINE_HW_IS_UP_RF2: ModuleTypeInfo(
        typ=PLATINE_HW_IS_UP_RF2,
        description="RF-Tag Leser V2",
        ns=0,
        na=0,
        ng=0,
        nm=10,
        sw1=2,
        sw2=0,
        swIPK1=4,
        swIPK2=4,
        i0=55,
    ),
}


def get_module_type_info(module_type: int) -> ModuleTypeInfo | None:
    """Return the module type information for a given module type."""
    return MODULE_TYPES.get(module_type)
